import { oberknechtAPI } from "oberknecht-api";
import { oberknechtEmitter, oberknechtActionEmitter, oberknechtQueueEmitter } from "oberknecht-emitters";
import { clearchatMessage, globaluserstateMessage, noticeMessage, privmsgMessage, usernoticeMessage, userstateMessage, whisperMessage } from "../parser/Message.Types";
declare const onPRIVMSGcallback: (privmsg: privmsgMessage, channelName: string, senderUsername: string, messageText: string) => void;
declare const onGLOBALUSERSTATEcallback: (globaluserstate: globaluserstateMessage) => void;
declare const onCLEARCHATcallback: (clearchat: clearchatMessage) => void;
declare const onNOTICEcallback: (notice: noticeMessage) => void;
declare const onUSERNOTICEcallback: (usernotice: usernoticeMessage) => void;
declare const onUSERSTATEcallback: (userstate: userstateMessage) => void;
declare const onWHISPERcallback: (whisper: whisperMessage) => void;
declare const onErrorcallback: (error: Error) => void;
declare const onAutojoinCallback: (channels: string[]) => void;
declare const onEmptyCallback: () => void;
import { clientOptions } from "../types/oberknechtClient.clientOptions";
import { i } from "..";
export declare class oberknechtClient {
    #private;
    get options(): any;
    get clientData(): any;
    get _allIndex(): typeof i;
    prefix: any;
    API: oberknechtAPI;
    OberknechtEmitter: oberknechtEmitter;
    OberknechtActionEmitter: oberknechtActionEmitter;
    OberknechtQueueEmitter: oberknechtQueueEmitter;
    get symbol(): string;
    get uptime(): number;
    get channels(): any;
    get wsUptime(): number;
    get wsNum(): any;
    get wsConnections(): any;
    get isConnected(): boolean;
    static get symbol(): any;
    static get uptime(): any;
    static get channels(): any;
    static get wsUptime(): any;
    static get wsNum(): any;
    static get wsConnections(): any;
    static get isConnected(): any;
    static get options(): clientOptions;
    static get clientData(): any;
    static get _allIndex(): any;
    _options: clientOptions;
    constructor(options: clientOptions);
    connect(): Promise<void>;
    destroy(): Promise<void>;
    privmsg: (channel: string, message: string) => Promise<unknown>;
    send: (channel: string, message: string) => Promise<unknown>;
    say: (channel: string, message: string) => Promise<unknown>;
    action: (channel: string, message: string) => Promise<unknown>;
    sendRaw: (message: string) => Promise<unknown>;
    join: (channel: string) => Promise<unknown>;
    joinAll: (channels: string | string[]) => Promise<unknown>;
    part: (channel: string) => Promise<unknown>;
    partAll: (channels: string | string[]) => Promise<void>;
    ping: () => Promise<unknown>;
    whisper: (targetUser: string, message: string, customtoken?: string) => Promise<any>;
    shoutout: (fromBroadcasterID: string, toBroadcasterID: string, customToken?: string) => Promise<void>;
    timeout: (broadcasterID: string, targetUserID: string, duration: number, reason?: string, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/ban").banResponse>;
    ban: (broadcasterID: string, targetUserID: string, reason: string, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/ban").banResponse>;
    unban: (broadcasterID: string, targetUserID: string, customToken?: string) => Promise<void>;
    untimeout: (broadcasterID: string, targetUserID: string, customToken?: string) => Promise<void>;
    deleteMessage: (broadcasterID: string, messageID: string, customToken?: string) => Promise<void>;
    announce: (broadcasterID: string, message: string, color: "blue" | "green" | "orange" | "purple" | "primary", customToken?: string) => Promise<void>;
    updateChatSettings: (broadcasterID: string, settings: import("oberknecht-api/lib-ts/types/endpoints/chatSettings").chatSettingEntry, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/chatSettings").chatSettingsResponse>;
    slow: (broadcasterID: string, waitTime: number, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/chatSettings").chatSettingsResponse>;
    slowOff: (broadcasterID: string, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/chatSettings").chatSettingsResponse>;
    followers: (broadcasterID: string, duration?: number, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/chatSettings").chatSettingsResponse>;
    followersOff: (broadcasterID: string, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/chatSettings").chatSettingsResponse>;
    subscribers: (broadcasterID: string, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/chatSettings").chatSettingsResponse>;
    subscribersOff: (broadcasterID: string, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/chatSettings").chatSettingsResponse>;
    r9k: (broadcasterID: string, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/chatSettings").chatSettingsResponse>;
    uniqueChat: (broadcasterID: string, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/chatSettings").chatSettingsResponse>;
    r9kOff: (broadcasterID: string, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/chatSettings").chatSettingsResponse>;
    uniqueChatOff: (broadcasterID: string, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/chatSettings").chatSettingsResponse>;
    chatdelay: (broadcasterID: string, duration: 2 | 4 | 6, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/chatSettings").chatSettingsResponse>;
    chatdelayOff: (broadcasterID: string, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/chatSettings").chatSettingsResponse>;
    getChatSettings: (broadcasterID: string, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/chatSettings").chatSettingsResponse>;
    mod: (userID: string, broadcasterID?: undefined, customToken?: string) => Promise<void>;
    unmod: (broadcasterID: string, userID: string, customToken?: string) => Promise<void>;
    vip: (toUserID: string, broadcasterID?: undefined, customToken?: string) => Promise<void>;
    unvip: (broadcasterID: string, userID: string, customToken?: string) => Promise<void>;
    updateColor: (color: string, customToken?: string) => Promise<void>;
    getColor: (userIDs: string | string[], customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/color").getColorResponse>;
    raid: (fromBroadcasterID: string, toBroadcasterID: string, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/raid").raidResponse>;
    unraid: (broadcasterID: string, customToken?: string) => Promise<void>;
    getStreams: (filters: import("oberknecht-api/lib-ts/types/endpoints/getStreams").getStreamsFiltersType, customToken?: string) => Promise<import("oberknecht-api/lib-ts/types/endpoints/getStreams").getStreamsResponse>;
    getuser: (login: string | undefined, id: string | undefined, noautofilterids: boolean) => Promise<import("oberknecht-api/lib-ts/types/endpoints/_getUsers").userEntry>;
    getusers: (logins: string | string[] | undefined, ids: string | string[] | undefined, noautofilterids: boolean) => Promise<import("oberknecht-api/lib-ts/types/endpoints/_getUsers").userEntry[]>;
    getusername: (userid: string) => Promise<unknown>;
    getuserid: (username: string) => Promise<unknown>;
    on: (eventName: string | string[], callback: Function) => void;
    addListener: (eventName: string | string[], callback: Function) => void;
    off: (eventName: string, callback: Function) => void;
    remove: (eventName: string, callback: Function) => void;
    removeAllListeners: (eventName: string) => void;
    emit: (eventName: string | string[], ...args: any) => void;
    onPRIVMSG: (callback: typeof onPRIVMSGcallback) => void;
    onGLOBALUSERSTATE: (callback: typeof onGLOBALUSERSTATEcallback) => void;
    onCLEARCHAT: (callback: typeof onCLEARCHATcallback) => void;
    onNOTICE: (callback: typeof onNOTICEcallback) => void;
    onUSERNOTICE: (callback: typeof onUSERNOTICEcallback) => void;
    onUSERSTATE: (callback: typeof onUSERSTATEcallback) => void;
    onWHISPER: (callback: typeof onWHISPERcallback) => void;
    onError: (callback: typeof onErrorcallback) => void;
    onReady: (callback: typeof onEmptyCallback) => void;
    onClose: (callback: typeof onEmptyCallback) => void;
    onAutojoin: (callback: typeof onAutojoinCallback) => void;
}
export {};
