"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.userstateMessage = void 0;
let oberknecht_utils_1 = require("oberknecht-utils");
let __1 = require("..");
class userstateMessage {
    sym;
    _raw;
    timestamp;
    IRCCommand;
    IRCParameters;
    IRCMessageParts;
    IRCMessagePrefix;
    badgeInfo;
    badges;
    badgesRaw;
    senderUserName;
    senderDisplayName;
    senderUserType;
    senderUserColor;
    channelNameRaw;
    channelName;
    emoteSets;
    emoteSetsRaw;
    isMod;
    isModRaw;
    isSubscriber;
    isSubscriberRaw;
    turbo;
    turboRaw;
    messageID;
    constructor(sym, rawMessage) {
        const dn = Date.now();
        this.timestamp = dn;
        this.sym = sym;
        this._raw = rawMessage;
        this.IRCCommand = (0, oberknecht_utils_1.messageCommand)(rawMessage);
        this.IRCMessageParts = this._raw.split(" ");
        this.IRCParameters = (0, oberknecht_utils_1.messageParameters)(this._raw);
        this.IRCMessagePrefix = (0, oberknecht_utils_1.messagePrefix)(this._raw);
        this.senderUserName = (0, oberknecht_utils_1.messageUser)(this.IRCMessagePrefix);
        this.badgeInfo = this.IRCParameters["badge-info"];
        this.badgesRaw = this.IRCParameters["badges"];
        this.badges = (0, oberknecht_utils_1.messageBadges)(this.badgesRaw);
        this.senderUserName = (0, oberknecht_utils_1.messageUser)(this.IRCMessagePrefix);
        this.senderDisplayName = this.IRCParameters["display-name"] ?? undefined;
        this.senderUserType = this.IRCParameters["user-type"] ?? undefined;
        this.senderUserColor = this.IRCParameters["color"] ?? undefined;
        this.channelNameRaw = this.IRCMessageParts[3] ?? undefined;
        this.channelName = (__1.i.utils.cleanChannelName(this.channelNameRaw));
        this.emoteSetsRaw = this.IRCParameters["emote-sets"];
        this.emoteSets = (0, oberknecht_utils_1.messageEmoteSets)(this.emoteSetsRaw);
        this.isModRaw = this.IRCParameters["mod"];
        this.isMod = (this.isModRaw === "1");
        this.isSubscriberRaw = this.IRCParameters["subscriber"];
        this.isSubscriber = (this.isSubscriberRaw === "1");
        this.turboRaw = this.IRCParameters["turbo"];
        this.turbo = (this.turboRaw === "1");
        this.messageID = this.IRCParameters["id"] ?? undefined;
    }
    ;
}
exports.userstateMessage = userstateMessage;
;
